fieldLayouts:
  2aac7003-4ca0-4dae-89b8-45996b2c15b8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 70562311-a4e1-453d-aa41-608f6017aabe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 27ec8eb2-b037-4427-b5de-ca356fb40a0e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 829f8297-732f-482d-96c7-9f9ae47cf6b4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f0424f7b-3a3f-41b4-ba50-141dbb749a8e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f47a457-3144-4cc3-ba1d-aa76a7094847
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: bc3443e1-748d-41d2-9b32-b085552cb440
        userCondition: null
handle: archiv
hasTitleField: false
name: Archiv
section: b373d66a-5a09-4164-a51a-bbbef0102a75
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
