fieldLayouts:
  97500b3a-619a-4d4f-af86-29050380fc7a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5b25ff50-7547-4fb0-ae39-d98f60cfd71f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 086259da-3672-47af-a708-cf80ee82c01e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a3416e6-0690-45d1-9842-c24edcaebed5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 27ec8eb2-b037-4427-b5de-ca356fb40a0e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4ac93f6-026c-4b15-b4fc-105bf53db005
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Featured Projects'
            type: craft\fieldlayoutelements\Heading
            uid: 229da3bd-1eea-4dcf-8a82-a69ccc4d7341
            userCondition: null
          -
            elementCondition: null
            fieldUid: 24f1ca91-8849-41c2-b4d9-f7e335886226
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 533fa4f7-0a44-4cbe-950a-2eceacd17c15
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b1df43c-1bba-435b-8d56-1b4260d2efb9
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: d03399df-cbbc-4519-949d-ae47810ffc53
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
