columnSuffix: ipwofvgv
contentColumnType: text
fieldGroup: 70fb5bd9-06ba-44bc-ac8e-4d97f1340d05
handle: businessDetails
instructions: "Caretta + Gitz AG\t\t\t\r\nBaumanagement \t\t\t\t\r\nGesamtplanung"
name: 'Business Details'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Simple.json
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
