columnSuffix: null
contentColumnType: string
fieldGroup: 0404121f-3b43-4edf-8f91-484cf9e22e05
handle: projectGallery
instructions: null
name: 'Project Gallery'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:8427f64a-7a41-4982-9210-df04b8400923'
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: 0
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:8427f64a-7a41-4982-9210-df04b8400923'
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Add Image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
