defaultPlacement: end
enableVersioning: true
handle: referenzen
name: Referenzen
propagationMethod: all
siteSettings:
  f70b9a5b-18df-4c74-9883-5a97fbf5f7f4:
    enabledByDefault: true
    hasUrls: true
    template: referenzen/_entry
    uriFormat: referenzen
type: single
